spring:
  profiles:
    active: h2memory
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
  # datasource:
  #   url: jdbc:h2:mem:testdb
  #   driverClassName: org.h2.Driver
  #   username: sa
  #   password: password
  #   jpa:
  #     database-platform: org.hibernate.dialect.H2Dialect
  # h2:
  #   console:
  #     enabled: true

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
              # SQL: DEBUG
            # sql: trace
      # springframework:
      #   orm:
      #     jpa: DEBUG
      #   transaction: DEBUG
      #   web: DEBUG
    com:
      giffing:
        bucket4j:
          spring:
            boot:
              starter: DEBUG

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      token-prefix: Bearer 
      expiration: 86400000